### ISSUE TITLE
Normalize value before being stored in redux

### ISSUE THREAD

**Issue by endygower** [traveloka/soya-form#53]
**Is your feature request related to a problem? Please describe.**
1. I need to limit user input for example: percentage value (0 - 100)
If user input 101, there's no way I can change the value before it was stored in redux
2. when combined using [https://www.npmjs.com/package/react-text-mask](react-text-mask), I would also like to format how the value is going to be stored
react-text-mask will pass formatted value like 1,234.56 but I would like to save it as 123456 (no format)
3. and to add to point 2, when combined using onChange handler, I would like to validate this as numeric not as preformatted string

Here is what I came up for the points above, eventhough none of these approaches fit my case
1. This is resolved using `type="numeric"`. But by using this approach, I cannot use react-text-mask on numeric input (I would like to have exactly 2 decimal, both on stored and displayed value)
2. There's props called `parseValue` for field level, but this props unfortunately only works on `form.submit`
3. This can be easily resolved by creating validator to match the format

**Describe the solution you'd like**
A normalize function as in redux-form
> A function to convert whatever value the user has entered into the value that you want stored in the Redux store for the field. For instance, if you want the value to be in all uppercase, you would pass value => value.toUpperCase().

You can find the full documentation here
https://redux-form.com/8.1.0/docs/api/field.md/#-code-normalize-value-previousvalue-allvalues-previousallvalues-name-gt-nextvalue-code-optional-

**Comment by fawwaz** [comment]
cc : @sayuti-daniel :bowing_man:
